run:
  timeout: 5m
  tests: true

linters-settings:
  govet:
    shadow: false
  gocyclo:
    min-complexity: 30
  dupl:
    threshold: 200
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 200
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - emptyStringTest
      - elseif

linters:
  enable:
    - errcheck
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
  disable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goimports
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - stylecheck
    - unconvert
    - unparam
    - whitespace

issues:
  exclude-dirs:
    - custom-rules-examples
  exclude-rules:
    - path: custom-rules-examples/
      linters:
        - unused
    - path: _test\.go
      linters:
        - errcheck
    - linters:
        - lll
      source: "^//go:generate "
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0 